on:
  push:
    branches:
      - main
name: Deploy
jobs:
  deploy_blog:
    name: Deploy blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          # node_modules 캐싱
          path: '**/node_modules'
          # lock file을 cache 무효화 기준으로 설정
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          # key가 유효하지 않은 경우
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        # 캐시가 없다면 새로 설치
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: deploy
          PUBLISH_DIR: ./public
